# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: crossplane-cluster-1
  region: eu-central-1

#nodeGroups:
#  - name: ng-1
#    instanceType: m5.large
#    desiredCapacity: 1

managedNodeGroups:
- name: spot
  instanceTypes: ["t4g.medium","t4g.small"]
  spot: true
  minSize: 2
  maxSize: 4

managedNodeGroups:
- name: spot
  instanceTypes: ["t4g.medium","t4g.small"]
  spot: true
  minSize: 2
  maxSize: 4


#cloudWatch:
    #clusterLogging:
        # enable specific types of cluster control plane logs
        # enableTypes: []
        # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
        # supported special values: "*" and "all"