apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: LaunchTemplate
metadata:
  name: test-crossplane-obj
spec:
  forProvider:
    launchTemplateData:
      imageID: ami-0a485299eeb98b979 #Amazon Linux 2023 AMI
      instanceMarketOptions:
        marketType: spot
        spotOptions:
          instanceInterruptionBehavior: terminate
          spotInstanceType: one-time
      keyName: web-key
      instanceType: m5.large
      tagSpecifications:
        - resourceType: volume
          tags:
            - key: original
              value: "1"
      userData: 'IyEvYmluL2Jhc2gNCnN1ZG8geXVtIHVwZGF0ZSAteQ0Kc3VkbyB5dW0gaW5zdGFsbCBuZ2lueCAteQ0Kc3VkbyBzeXN0ZW1jdGwgc3RhcnQgbmdpbngNCnN1ZG8gc3lzdGVtY3RsIGVuYWJsZSBuZ2lueA0Kc3VkbyBzeXN0ZW1jdGwgc3RhdHVzIG5naW54DQo='
    region: eu-central-1
    launchTemplateName: test-crossplane-obj
  writeConnectionSecretToRef:
    name: ec2-secret
    namespace: crossplane-system
  providerConfigRef:
    name: crossplane-default
