apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: argo-cd
spec:
# rollbackLimit: 3
  forProvider:
    chart:
      name: argo-cd
      repository: https://argoproj.github.io/argo-helm
      version: 4.8.3 ## To use devlopment versions, set ">0.0.0-0"
    namespace: argo-cd
  providerConfigRef:
    name: helm-provider