apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: ingress-nginx
spec:
# rollbackLimit: 3
  forProvider:
    chart:
      name: ingress-nginx
      repository: https://kubernetes.github.io/ingress-nginx
      version: 4.8.3 ## To use devlopment versions, set ">0.0.0-0"
    namespace: ingress-nginx
  providerConfigRef:
    name: helm-provider