site_name: Crossplane Labs
site_url: https://example.com/
repo_url: https://github.com/itumor/crossplane-labs
nav:
  - Home: index.md
  - About: about.md
theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
  nav_style: dark
